### ISSUE TITLE
If the view is a desert, there shouldn't be a coconut tree there

### ISSUE THREAD

**Issue by K4zoku** [NNBnh/dino-assets#2]
As the title says, the desert should not have coconut trees. I think I should change to the shadow of the cactus in the distance or delete the coconut tree completely and add nothing.

**Comment by NNBnh** [comment]
Tada! :tada::tada::tada:

![Sandy2](https://github.com/NNBnh/dino-assets/blob/main/sandy2.png?raw=true)
